# Generated by Django 5.0 on 2024-01-05 09:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0004_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
