# Generated by Django 5.0 on 2024-01-06 10:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0006_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
