# Generated by Django 5.0 on 2024-01-07 19:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0007_delete_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tweet",
            options={"ordering": ["-id"]},
        ),
    ]
